steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '--build-arg', 'NODE_ENV=${_ENV}',
            '--build-arg', 'FRAME_URL=${_FRAME_URL}',
            '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME/vynos/${_ENV}:$COMMIT_SHA',
            '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME/vynos/${_ENV}:latest',
            '.'
          ]
    dir: 'vynos'
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME/vynos/${_ENV}:$COMMIT_SHA"]
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - set
    - image
    - deployment
    - ${_DEPLOYMENT_NAME}
    - '*=gcr.io/$PROJECT_ID/$REPO_NAME/vynos/${_ENV}:$COMMIT_SHA'
    env:  [
            'CLOUDSDK_COMPUTE_ZONE=us-east4-a',
            'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'
          ]
images: [
          'gcr.io/$PROJECT_ID/$REPO_NAME/vynos/${_ENV}:$COMMIT_SHA',
        ]
