steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '--build-arg', 'NODE_ENV=${_ENV}',
            '--build-arg', 'FRAME_URL=https://${_FRAME_DOMAIN}',
            '--build-arg', 'API_URL=${_API_URL}',
            '--build-arg', 'NETWORK_NAME=${_NETWORK_NAME}',
            '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME/${_PROJECT}/${_ENV}:$COMMIT_SHA',
            '.'
          ]
    dir: '${_PROJECT}'

  - name: 'gcr.io/$PROJECT_ID/$REPO_NAME/${_PROJECT}/${_ENV}:$COMMIT_SHA'
    args: [ 'cp', '-r', './dist/', 'dist']
    dir: '${_PROJECT}'

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ["-m", "rsync", "-r", "-c", "-d", "./dist/", "gs://${_FRAME_DOMAIN}"]
    dir: '${_PROJECT}'
