#!/bin/bash
# STOP! Before going any further, think: are you going to regret the decision
# to write this script?
#     Deciding to write this in bash was not one of my better decisions.
#     -- https://twitter.com/alex_gaynor/status/369892494114164736

IFS="`printf "\n\t"`"
set -u
cd "$(dirname "$0")"

yarn --production=false --frozen-lockfile --cache-folder /root/.yarn && exit 0

echo
echo "WARNING: Yarn install failed, but this happens sometimes."
echo "WARNING: Giving it one more try, just for good measure."
echo

yarn --production=false --frozen-lockfile --cache-folder /root/.yarn
exit $?
